#!/usr/bin/env -S docker build --compress -t test -f

FROM debian:stable

RUN apt update
RUN apt install -y \
	binutils clang lld make build-essential

WORKDIR /data
COPY ./ ./
RUN make all
ENV LD_LIBRARY_PATH "."
